### ISSUE TITLE
Does the repo still valid and active for the unet project

### ISSUE THREAD

**Issue by aiLover2** [YuzhouPeng/unet-tensorrt#15]
I have faced some issue in testing the repo, I downloaded the [pretrained weight](https://github.com/milesial/Pytorch-UNet/releases/tag/v3.0) from the main repo and change your convert_wt.py file as the below and get the weights

``` python
import torch
from torch import nn
import torchvision
import os
import struct
from torchsummary import summary
from unet import UNet


def main():
    print('cuda device count: ', torch.cuda.device_count())
    net = UNet(n_channels=3, n_classes=2, bilinear=False)
    device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')

    net.to(device=device)
    net.load_state_dict(torch.load(
        'unet_carvana_scale1.0_epoch2.pth',
        map_location=device))

    net = net.eval()
    print('model: ', net)
    # print('state dict: ', net.state_dict().keys())
    # tmp = torch.ones(1, 3, 224, 224).to('cuda:0')
    # print('input: ', tmp)
    # out = net(tmp)

    # print('output:', out)

    summary(net, (3, 224, 224))
    # return
    f = open("unet.wts", 'w')
    f.write("{}\n".format(len(net.state_dict().keys())))
    for k, v in net.state_dict().items():
        print('key: ', k)
        print('value: ', v.shape)
        vr = v.reshape(-1).cpu().numpy()
        f.write("{} {}".format(k, len(vr)))
        for vv in vr:
            f.write(" ")
            f.write(struct.pack(">f", float(vv)).hex())
        f.write("\n")


if __name__ == '__main__':
    main()

```
After that I have changed some lines as the below in the c++ file:
```c++
#define BILINEAR false
```

```c++
std::map<std::string, Weights> weightMap = loadWeights("/path/to/unet.wts");
```

You can see the below report from the running the program:
```c++
Loading weights: /home/saeed/Documents/IRIS-PROJECT/projects/Pytorch-UNet/unet.wts
[05/20/2022-22:52:54] [05/20/2022-22:52:54] [05/20/2022-22:52:54] [05/20/2022-22:52:54] [05/20/2022-22:52:54] [05/20/2022-22:52:54] [05/20/2022-22:52:54] [05/20/2022-22:52:54] [05/20/2022-22:52:54] [05/20/2022-22:52:54] [05/20/2022-22:52:54] [05/20/2022-22:52:54] [05/20/2022-22:52:54] [05/20/2022-22:52:54] [05/20/2022-22:52:54] [05/20/2022-22:52:54] [05/20/2022-22:52:54] [05/20/2022-22:52:54] [05/20/2022-22:52:54] [05/20/2022-22:52:54] [05/20/2022-22:52:54] [05/20/2022-22:52:54] [05/20/2022-22:52:54] [05/20/2022-22:52:54] [05/20/2022-22:52:54] [05/20/2022-22:52:54] [05/20/2022-22:52:54] [05/20/2022-22:52:54] [05/20/2022-22:52:54] [05/20/2022-22:52:54] [05/20/2022-22:52:54] [05/20/2022-22:52:54] [05/20/2022-22:52:54] [05/20/2022-22:52:54] [05/20/2022-22:52:54] [05/20/2022-22:52:54] [05/20/2022-22:52:54] [05/20/2022-22:52:54] [05/20/2022-22:52:54] [05/20/2022-22:52:54] [05/20/2022-22:52:54] [05/20/2022-22:52:54] [05/20/2022-22:52:54] [05/20/2022-22:52:54] [05/20/2022-22:52:54] [05/20/2022-22:52:54] [05/20/2022-22:52:54] [05/20/2022-22:52:54] [05/20/2022-22:52:54] [05/20/2022-22:52:54] [05/20/2022-22:52:54] [05/20/2022-22:52:54] [05/20/2022-22:52:54] [05/20/2022-22:52:54] [05/20/2022-22:52:54] [05/20/2022-22:52:54] [05/20/2022-22:52:54] [05/20/2022-22:52:54] [05/20/2022-22:52:54] [05/20/2022-22:52:54] [05/20/2022-22:52:54] [05/20/2022-22:52:54] [05/20/2022-22:52:54] [05/20/2022-22:52:54] [05/20/2022-22:52:54] [05/20/2022-22:52:54] [05/20/2022-22:52:54] [05/20/2022-22:52:54] [05/20/2022-22:52:54] [05/20/2022-22:52:54] [05/20/2022-22:52:54] [05/20/2022-22:52:54] [05/20/2022-22:52:54] [05/20/2022-22:52:54] [05/20/2022-22:52:54] [05/20/2022-22:52:54] [05/20/2022-22:52:54] [05/20/2022-22:52:54] [05/20/2022-22:52:54] [05/20/2022-22:52:54] [05/20/2022-22:52:54] [05/20/2022-22:52:54] [05/20/2022-22:52:54] [05/20/2022-22:52:54] [05/20/2022-22:52:54] [05/20/2022-22:52:54] [05/20/2022-22:52:54] [05/20/2022-22:52:54] [05/20/2022-22:52:54] [05/20/2022-22:52:54] set name out
Building engine, please wait for a while...
[05/20/2022-22:52:54] [05/20/2022-22:52:54] [05/20/2022-22:52:54] [05/20/2022-22:52:54] Build engine successfully!
[E] [TRT] 3: (Unnamed Layer* 28) [Convolution]:kernel weights has count 4718592 but 2359296 was expected
[E] [TRT] 4: (Unnamed Layer* 28) [Convolution]: count of 4718592 weights in kernel, but kernel dimensions (3,3) with 512 input channels, 512 output channels and 1 groups were specified. Expected Weights count is 512 * 3*3 * 512 / 1 = 2359296
[E] [TRT] 4: [convolutionNode.cpp::computeOutputExtents::39] Error Code 4: Internal Error ((Unnamed Layer* 28) [Convolution]: number of kernel weights does not match tensor dimensions)
[E] [TRT] 3: (Unnamed Layer* 28) [Convolution]:kernel weights has count 4718592 but 2359296 was expected
[E] [TRT] 4: (Unnamed Layer* 28) [Convolution]: count of 4718592 weights in kernel, but kernel dimensions (3,3) with 512 input channels, 512 output channels and 1 groups were specified. Expected Weights count is 512 * 3*3 * 512 / 1 = 2359296
[E] [TRT] 4: [convolutionNode.cpp::computeOutputExtents::39] Error Code 4: Internal Error ((Unnamed Layer* 28) [Convolution]: number of kernel weights does not match tensor dimensions)
[E] [TRT] 3: (Unnamed Layer* 28) [Convolution]:kernel weights has count 4718592 but 2359296 was expected
[E] [TRT] 4: (Unnamed Layer* 28) [Convolution]: count of 4718592 weights in kernel, but kernel dimensions (3,3) with 512 input channels, 512 output channels and 1 groups were specified. Expected Weights count is 512 * 3*3 * 512 / 1 = 2359296
[E] [TRT] 4: [convolutionNode.cpp::computeOutputExtents::39] Error Code 4: Internal Error ((Unnamed Layer* 28) [Convolution]: number of kernel weights does not match tensor dimensions)
[E] [TRT] 3: (Unnamed Layer* 28) [Convolution]:kernel weights has count 4718592 but 2359296 was expected
[E] [TRT] 4: (Unnamed Layer* 28) [Convolution]: count of 4718592 weights in kernel, but kernel dimensions (3,3) with 512 input channels, 512 output channels and 1 groups were specified. Expected Weights count is 512 * 3*3 * 512 / 1 = 2359296
[E] [TRT] 4: [convolutionNode.cpp::computeOutputExtents::39] Error Code 4: Internal Error ((Unnamed Layer* 28) [Convolution]: number of kernel weights does not match tensor dimensions)
[E] [TRT] 3: (Unnamed Layer* 28) [Convolution]:kernel weights has count 4718592 but 2359296 was expected
[E] [TRT] 4: (Unnamed Layer* 28) [Convolution]: count of 4718592 weights in kernel, but kernel dimensions (3,3) with 512 input channels, 512 output channels and 1 groups were specified. Expected Weights count is 512 * 3*3 * 512 / 1 = 2359296
[E] [TRT] 4: [convolutionNode.cpp::computeOutputExtents::39] Error Code 4: Internal Error ((Unnamed Layer* 28) [Convolution]: number of kernel weights does not match tensor dimensions)
[E] [TRT] 3: (Unnamed Layer* 28) [Convolution]:kernel weights has count 4718592 but 2359296 was expected
[E] [TRT] 4: (Unnamed Layer* 28) [Convolution]: count of 4718592 weights in kernel, but kernel dimensions (3,3) with 512 input channels, 512 output channels and 1 groups were specified. Expected Weights count is 512 * 3*3 * 512 / 1 = 2359296
[E] [TRT] 4: [convolutionNode.cpp::computeOutputExtents::39] Error Code 4: Internal Error ((Unnamed Layer* 28) [Convolution]: number of kernel weights does not match tensor dimensions)
[E] [TRT] 3: (Unnamed Layer* 28) [Convolution]:kernel weights has count 4718592 but 2359296 was expected
[E] [TRT] 4: (Unnamed Layer* 28) [Convolution]: count of 4718592 weights in kernel, but kernel dimensions (3,3) with 512 input channels, 512 output channels and 1 groups were specified. Expected Weights count is 512 * 3*3 * 512 / 1 = 2359296
[E] [TRT] 4: [convolutionNode.cpp::computeOutputExtents::39] Error Code 4: Internal Error ((Unnamed Layer* 28) [Convolution]: number of kernel weights does not match tensor dimensions)
[E] [TRT] 3: (Unnamed Layer* 28) [Convolution]:kernel weights has count 4718592 but 2359296 was expected
[E] [TRT] 4: (Unnamed Layer* 28) [Convolution]: count of 4718592 weights in kernel, but kernel dimensions (3,3) with 512 input channels, 512 output channels and 1 groups were specified. Expected Weights count is 512 * 3*3 * 512 / 1 = 2359296
[E] [TRT] 4: [convolutionNode.cpp::computeOutputExtents::39] Error Code 4: Internal Error ((Unnamed Layer* 28) [Convolution]: number of kernel weights does not match tensor dimensions)
[E] [TRT] 3: (Unnamed Layer* 28) [Convolution]:kernel weights has count 4718592 but 2359296 was expected
[E] [TRT] 4: (Unnamed Layer* 28) [Convolution]: count of 4718592 weights in kernel, but kernel dimensions (3,3) with 512 input channels, 512 output channels and 1 groups were specified. Expected Weights count is 512 * 3*3 * 512 / 1 = 2359296
[E] [TRT] 4: [convolutionNode.cpp::computeOutputExtents::39] Error Code 4: Internal Error ((Unnamed Layer* 28) [Convolution]: number of kernel weights does not match tensor dimensions)
[E] [TRT] 3: (Unnamed Layer* 28) [Convolution]:kernel weights has count 4718592 but 2359296 was expected
[E] [TRT] 4: (Unnamed Layer* 28) [Convolution]: count of 4718592 weights in kernel, but kernel dimensions (3,3) with 512 input channels, 512 output channels and 1 groups were specified. Expected Weights count is 512 * 3*3 * 512 / 1 = 2359296
[E] [TRT] 4: [convolutionNode.cpp::computeOutputExtents::39] Error Code 4: Internal Error ((Unnamed Layer* 28) [Convolution]: number of kernel weights does not match tensor dimensions)
[E] [TRT] 3: (Unnamed Layer* 28) [Convolution]:kernel weights has count 4718592 but 2359296 was expected
[E] [TRT] 4: (Unnamed Layer* 28) [Convolution]: count of 4718592 weights in kernel, but kernel dimensions (3,3) with 512 input channels, 512 output channels and 1 groups were specified. Expected Weights count is 512 * 3*3 * 512 / 1 = 2359296
[E] [TRT] 4: [convolutionNode.cpp::computeOutputExtents::39] Error Code 4: Internal Error ((Unnamed Layer* 28) [Convolution]: number of kernel weights does not match tensor dimensions)
[E] [TRT] 3: (Unnamed Layer* 28) [Convolution]:kernel weights has count 4718592 but 2359296 was expected
[E] [TRT] 4: (Unnamed Layer* 28) [Convolution]: count of 4718592 weights in kernel, but kernel dimensions (3,3) with 512 input channels, 512 output channels and 1 groups were specified. Expected Weights count is 512 * 3*3 * 512 / 1 = 2359296
[E] [TRT] 4: [convolutionNode.cpp::computeOutputExtents::39] Error Code 4: Internal Error ((Unnamed Layer* 28) [Convolution]: number of kernel weights does not match tensor dimensions)
[E] [TRT] 3: (Unnamed Layer* 28) [Convolution]:kernel weights has count 4718592 but 2359296 was expected
[E] [TRT] 4: (Unnamed Layer* 28) [Convolution]: count of 4718592 weights in kernel, but kernel dimensions (3,3) with 512 input channels, 512 output channels and 1 groups were specified. Expected Weights count is 512 * 3*3 * 512 / 1 = 2359296
[E] [TRT] 4: [convolutionNode.cpp::computeOutputExtents::39] Error Code 4: Internal Error ((Unnamed Layer* 28) [Convolution]: number of kernel weights does not match tensor dimensions)
[E] [TRT] 3: (Unnamed Layer* 28) [Convolution]:kernel weights has count 4718592 but 2359296 was expected
[E] [TRT] 4: (Unnamed Layer* 28) [Convolution]: count of 4718592 weights in kernel, but kernel dimensions (3,3) with 512 input channels, 512 output channels and 1 groups were specified. Expected Weights count is 512 * 3*3 * 512 / 1 = 2359296
[E] [TRT] 4: [convolutionNode.cpp::computeOutputExtents::39] Error Code 4: Internal Error ((Unnamed Layer* 28) [Convolution]: number of kernel weights does not match tensor dimensions)
[E] [TRT] 3: (Unnamed Layer* 28) [Convolution]:kernel weights has count 4718592 but 2359296 was expected
[E] [TRT] 4: (Unnamed Layer* 28) [Convolution]: count of 4718592 weights in kernel, but kernel dimensions (3,3) with 512 input channels, 512 output channels and 1 groups were specified. Expected Weights count is 512 * 3*3 * 512 / 1 = 2359296
[E] [TRT] 4: [convolutionNode.cpp::computeOutputExtents::39] Error Code 4: Internal Error ((Unnamed Layer* 28) [Convolution]: number of kernel weights does not match tensor dimensions)
[E] [TRT] 3: (Unnamed Layer* 28) [Convolution]:kernel weights has count 4718592 but 2359296 was expected
[E] [TRT] 4: (Unnamed Layer* 28) [Convolution]: count of 4718592 weights in kernel, but kernel dimensions (3,3) with 512 input channels, 512 output channels and 1 groups were specified. Expected Weights count is 512 * 3*3 * 512 / 1 = 2359296
[E] [TRT] 4: [convolutionNode.cpp::computeOutputExtents::39] Error Code 4: Internal Error ((Unnamed Layer* 28) [Convolution]: number of kernel weights does not match tensor dimensions)
[E] [TRT] 3: (Unnamed Layer* 28) [Convolution]:kernel weights has count 4718592 but 2359296 was expected
[E] [TRT] 4: (Unnamed Layer* 28) [Convolution]: count of 4718592 weights in kernel, but kernel dimensions (3,3) with 512 input channels, 512 output channels and 1 groups were specified. Expected Weights count is 512 * 3*3 * 512 / 1 = 2359296
[E] [TRT] 4: [convolutionNode.cpp::computeOutputExtents::39] Error Code 4: Internal Error ((Unnamed Layer* 28) [Convolution]: number of kernel weights does not match tensor dimensions)
[E] [TRT] 3: (Unnamed Layer* 28) [Convolution]:kernel weights has count 4718592 but 2359296 was expected
[E] [TRT] 4: (Unnamed Layer* 28) [Convolution]: count of 4718592 weights in kernel, but kernel dimensions (3,3) with 512 input channels, 512 output channels and 1 groups were specified. Expected Weights count is 512 * 3*3 * 512 / 1 = 2359296
[E] [TRT] 4: [convolutionNode.cpp::computeOutputExtents::39] Error Code 4: Internal Error ((Unnamed Layer* 28) [Convolution]: number of kernel weights does not match tensor dimensions)
[E] [TRT] 3: (Unnamed Layer* 28) [Convolution]:kernel weights has count 4718592 but 2359296 was expected
[E] [TRT] 4: (Unnamed Layer* 28) [Convolution]: count of 4718592 weights in kernel, but kernel dimensions (3,3) with 512 input channels, 512 output channels and 1 groups were specified. Expected Weights count is 512 * 3*3 * 512 / 1 = 2359296
[E] [TRT] 4: [convolutionNode.cpp::computeOutputExtents::39] Error Code 4: Internal Error ((Unnamed Layer* 28) [Convolution]: number of kernel weights does not match tensor dimensions)
[E] [TRT] 3: (Unnamed Layer* 28) [Convolution]:kernel weights has count 4718592 but 2359296 was expected
[E] [TRT] 4: (Unnamed Layer* 28) [Convolution]: count of 4718592 weights in kernel, but kernel dimensions (3,3) with 512 input channels, 512 output channels and 1 groups were specified. Expected Weights count is 512 * 3*3 * 512 / 1 = 2359296
[E] [TRT] 4: [convolutionNode.cpp::computeOutputExtents::39] Error Code 4: Internal Error ((Unnamed Layer* 28) [Convolution]: number of kernel weights does not match tensor dimensions)
[E] [TRT] 3: (Unnamed Layer* 28) [Convolution]:kernel weights has count 4718592 but 2359296 was expected
[E] [TRT] 4: (Unnamed Layer* 28) [Convolution]: count of 4718592 weights in kernel, but kernel dimensions (3,3) with 512 input channels, 512 output channels and 1 groups were specified. Expected Weights count is 512 * 3*3 * 512 / 1 = 2359296
[E] [TRT] 4: [convolutionNode.cpp::computeOutputExtents::39] Error Code 4: Internal Error ((Unnamed Layer* 28) [Convolution]: number of kernel weights does not match tensor dimensions)
[E] [TRT] 3: (Unnamed Layer* 28) [Convolution]:kernel weights has count 4718592 but 2359296 was expected
[E] [TRT] 4: (Unnamed Layer* 28) [Convolution]: count of 4718592 weights in kernel, but kernel dimensions (3,3) with 512 input channels, 512 output channels and 1 groups were specified. Expected Weights count is 512 * 3*3 * 512 / 1 = 2359296
[E] [TRT] 4: [convolutionNode.cpp::computeOutputExtents::39] Error Code 4: Internal Error ((Unnamed Layer* 28) [Convolution]: number of kernel weights does not match tensor dimensions)
[E] [TRT] 3: (Unnamed Layer* 28) [Convolution]:kernel weights has count 4718592 but 2359296 was expected
[E] [TRT] 4: (Unnamed Layer* 28) [Convolution]: count of 4718592 weights in kernel, but kernel dimensions (3,3) with 512 input channels, 512 output channels and 1 groups were specified. Expected Weights count is 512 * 3*3 * 512 / 1 = 2359296
[E] [TRT] 4: [convolutionNode.cpp::computeOutputExtents::39] Error Code 4: Internal Error ((Unnamed Layer* 28) [Convolution]: number of kernel weights does not match tensor dimensions)
[E] [TRT] 3: (Unnamed Layer* 28) [Convolution]:kernel weights has count 4718592 but 2359296 was expected
[E] [TRT] 4: (Unnamed Layer* 28) [Convolution]: count of 4718592 weights in kernel, but kernel dimensions (3,3) with 512 input channels, 512 output channels and 1 groups were specified. Expected Weights count is 512 * 3*3 * 512 / 1 = 2359296
[E] [TRT] 4: [convolutionNode.cpp::computeOutputExtents::39] Error Code 4: Internal Error ((Unnamed Layer* 28) [Convolution]: number of kernel weights does not match tensor dimensions)
[E] [TRT] 3: (Unnamed Layer* 28) [Convolution]:kernel weights has count 4718592 but 2359296 was expected
[E] [TRT] 4: (Unnamed Layer* 28) [Convolution]: count of 4718592 weights in kernel, but kernel dimensions (3,3) with 512 input channels, 512 output channels and 1 groups were specified. Expected Weights count is 512 * 3*3 * 512 / 1 = 2359296
[E] [TRT] 4: [convolutionNode.cpp::computeOutputExtents::39] Error Code 4: Internal Error ((Unnamed Layer* 28) [Convolution]: number of kernel weights does not match tensor dimensions)
[E] [TRT] 3: (Unnamed Layer* 28) [Convolution]:kernel weights has count 4718592 but 2359296 was expected
[E] [TRT] 4: (Unnamed Layer* 28) [Convolution]: count of 4718592 weights in kernel, but kernel dimensions (3,3) with 512 input channels, 512 output channels and 1 groups were specified. Expected Weights count is 512 * 3*3 * 512 / 1 = 2359296
[E] [TRT] 4: [convolutionNode.cpp::computeOutputExtents::39] Error Code 4: Internal Error ((Unnamed Layer* 28) [Convolution]: number of kernel weights does not match tensor dimensions)
[E] [TRT] 3: (Unnamed Layer* 28) [Convolution]:kernel weights has count 4718592 but 2359296 was expected
[E] [TRT] 4: (Unnamed Layer* 28) [Convolution]: count of 4718592 weights in kernel, but kernel dimensions (3,3) with 512 input channels, 512 output channels and 1 groups were specified. Expected Weights count is 512 * 3*3 * 512 / 1 = 2359296
[E] [TRT] 4: [convolutionNode.cpp::computeOutputExtents::39] Error Code 4: Internal Error ((Unnamed Layer* 28) [Convolution]: number of kernel weights does not match tensor dimensions)
[E] [TRT] 3: (Unnamed Layer* 28) [Convolution]:kernel weights has count 4718592 but 2359296 was expected
[E] [TRT] 4: (Unnamed Layer* 28) [Convolution]: count of 4718592 weights in kernel, but kernel dimensions (3,3) with 512 input channels, 512 output channels and 1 groups were specified. Expected Weights count is 512 * 3*3 * 512 / 1 = 2359296
[E] [TRT] 4: [convolutionNode.cpp::computeOutputExtents::39] Error Code 4: Internal Error ((Unnamed Layer* 28) [Convolution]: number of kernel weights does not match tensor dimensions)
[E] [TRT] 3: (Unnamed Layer* 28) [Convolution]:kernel weights has count 4718592 but 2359296 was expected
[E] [TRT] 4: (Unnamed Layer* 28) [Convolution]: count of 4718592 weights in kernel, but kernel dimensions (3,3) with 512 input channels, 512 output channels and 1 groups were specified. Expected Weights count is 512 * 3*3 * 512 / 1 = 2359296
[E] [TRT] 4: [convolutionNode.cpp::computeOutputExtents::39] Error Code 4: Internal Error ((Unnamed Layer* 28) [Convolution]: number of kernel weights does not match tensor dimensions)
[E] [TRT] 3: (Unnamed Layer* 28) [Convolution]:kernel weights has count 4718592 but 2359296 was expected
[E] [TRT] 4: (Unnamed Layer* 28) [Convolution]: count of 4718592 weights in kernel, but kernel dimensions (3,3) with 512 input channels, 512 output channels and 1 groups were specified. Expected Weights count is 512 * 3*3 * 512 / 1 = 2359296
[E] [TRT] 4: [convolutionNode.cpp::computeOutputExtents::39] Error Code 4: Internal Error ((Unnamed Layer* 28) [Convolution]: number of kernel weights does not match tensor dimensions)
[E] [TRT] 3: (Unnamed Layer* 28) [Convolution]:kernel weights has count 4718592 but 2359296 was expected
[E] [TRT] 4: (Unnamed Layer* 28) [Convolution]: count of 4718592 weights in kernel, but kernel dimensions (3,3) with 512 input channels, 512 output channels and 1 groups were specified. Expected Weights count is 512 * 3*3 * 512 / 1 = 2359296
[E] [TRT] 4: [convolutionNode.cpp::computeOutputExtents::39] Error Code 4: Internal Error ((Unnamed Layer* 28) [Convolution]: number of kernel weights does not match tensor dimensions)
[E] [TRT] 4: [network.cpp::validate::2835] Error Code 4: Internal Error (Could not compute dimensions for (Unnamed Layer* 0) [Convolution]_output, because the network is not valid.)
unet: /home/saeed/Documents/IRIS-PROJECT/projects/unet-tensorrt/unet.cpp:216: void APIToModel(unsigned int, nvinfer1::IHostMemory**): Assertion `engine != nullptr' failed.
```

Could you please help about the issue?

---

I have also changed the logging file to be able to use latest tensorrt api such as the below(because the base class has marked this function as a noexcept we should have mark the virtual function as noexcept)

```c++
    virtual void log(Severity severity, nvinfer1::AsciiChar const* msg) noexcept
    {
        LogStreamConsumer(mReportableSeverity, severity) << "[TRT] " << std::string(msg) << std::endl;
    }
```

**Comment by YuzhouPeng** [comment]
This repo is valid for the old version of pytorch-unet v1(2020) https://github.com/milesial/Pytorch-UNet/tree/v1.0, and you can download pretrained weights from https://github.com/milesial/Pytorch-UNet/releases/download/v1.0/unet_carvana_scale1_epoch5.pth, I tried the old version pretrained weight and it succeed.

**Comment by aiLover2** [comment]
I have checked out the pytorch-unet to v1 tag.

```bash
$ git checkout v1.0
```

Also, I have created new environment and run 
```
pip install -r requirements.txt
```

But there was an issue in `gen_wts.py` as the below:

```
cuda device count:  1
Traceback (most recent call last):
  File "/home/saeed/Documents/IRIS-PROJECT/projects/Pytorch-UNet/gen_wts.py", line 38, in <module>
    main()
  File "/home/saeed/Documents/IRIS-PROJECT/projects/Pytorch-UNet/gen_wts.py", line 12, in main
    net = net.to('cuda:0')
AttributeError: 'collections.OrderedDict' object has no attribute 'to'
```

I was able to solve this as I have mentioned the code in my first [comment](https://github.com/YuzhouPeng/unet-tensorrt/issues/15#issue-1243483353) but in running the tensorrt now I can see that the previous error not shown but the generating engine is crashed in the below line:

https://github.com/YuzhouPeng/unet-tensorrt/blob/a7a6d81ddf1ed553a87d1bdbd83075c6b892dacb/unet.cpp#L216

It seems that the engine is `nullptr` and is not created correctly.

**Comment by aiLover2** [comment]
I can confirm that works and the problem was in the below line:

https://github.com/YuzhouPeng/unet-tensorrt/blob/a7a6d81ddf1ed553a87d1bdbd83075c6b892dacb/unet.cpp#L15

I have changed it to `false` but after a simple `git stash` I can see that everything works. Thanks for the help @YuzhouPeng

**Comment by YuzhouPeng** [comment]
> I can confirm that the specified weight works and the problem was in the below line:
> 
> https://github.com/YuzhouPeng/unet-tensorrt/blob/a7a6d81ddf1ed553a87d1bdbd83075c6b892dacb/unet.cpp#L15
> 
> I have changed it to `false` but after a simple `git stash` I can see that everything works. Thanks for the help @YuzhouPeng

Yes, the md5 is 8d160e0ec171340bd1b80f3096cbd5c9.

**Comment by YSUN-coder** [comment]
@aiLover2 Did you make it with the which pretrained model? v3.0 or v1.0? I checkout to v1.0 code in Pytorch-UNet, and used your gen_wts.py code for the v1.0 pretrained model. But I got:

```
 torch.Size([2, 64, 1, 1]).
	size mismatch for outc.conv.bias: copying a param with shape torch.Size([1]) from checkpoint, the shape in current model is torch.Size([2]).
```
